language: go

go:
- 1.12.1

os:
- linux
- osx

dist: trusty

sudo: false

install: true

script:
- go build
- go test -v facade/techniques/*

after_success:
- bash <(curl -s https://codecov.io/bash)
