language: go

go:
- 1.12.1

os:
- linux
- osx

dist: trusty

sudo: false

install: true

script:
- go test -race -coverprofile=coverage.txt -covermode=atomic
- env GO111MODULE=on go build
- env GO111MODULE=on go test facade/techniques/*

after_success:
- bash <(curl -s https://codecov.io/bash)