title = "全局配置"

[redis]
    addr = "redis:6379"
    password = ""
    db = 1
    poolSize = 10
    poolTimeout = 30

    expire=60

user-agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15"