version: "3"
services:
  api:
    image: facade
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
          - ./bin:/opt/app/bin
    ports:
      - 8080:8080
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
    command: ./bin/facade_server

  redis:
    container_name: redis
    image: redis:4-alpine
    networks:
      - backend
    command: ["redis-server", "--appendonly", "yes"]

    
# Networks to be created to facilitate communication between containers
networks:
  backend:   